name: videoannotator-environment
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- graphite2=1.3.10=hc526e54_0
- harfbuzz=1.5.0=h2545bd6_0
- libgfortran-ng=7.2.0=h9f7466a_2
- jasper=1.900.1=4
- blas=1.0=mkl
- bzip2=1.0.6=h6d464ef_2
- ca-certificates=2017.08.26=h1d4fec5_0
- cairo=1.14.10=hdf128ce_6
- certifi=2017.11.5=py35h9749603_0
- ffmpeg=3.4=h7264315_0
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=hab7d2ae_1
- glib=2.53.6=h5d9569c_2
- hdf5=1.10.2=hba1933b_1
- icu=58.2=h9c2bf20_1
- intel-openmp=2018.0.0=hc7b2577_8
- jpeg=9b=h024ee3a_2
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=8.2.0=hdf63c60_1
- libgfortran=3.0.0=1
- libopus=1.2.1=hb9ed12e_0
- libpng=1.6.32=hbd3595f_4
- libprotobuf=3.6.0=hdbcaa40_0
- libstdcxx-ng=8.2.0=hdf63c60_1
- libtiff=4.0.9=h28f6b97_0
- libvpx=1.6.1=h888fd40_0
- libxcb=1.12=hcd93eb1_4
- libxml2=2.9.4=h2e8b1d7_6
- mkl=2018.0.3=1
- mkl_fft=1.0.4=py35h4414c95_1
- mkl_random=1.0.1=py35h4414c95_1
- ncurses=6.0=h9df7e31_2
- numpy=1.15.1=py35h1d66e8a_0
- numpy-base=1.15.1=py35h81de0dd_0
- opencv=3.4.1=py35h6fd60c2_1
- openssl=1.0.2n=hb7f436b_0
- pcre=8.41=hc27e229_1
- pip=9.0.1=py35h7e7da9d_4
- pixman=0.34.0=hceecf20_3
- python=3.5.4=h417fded_24
- readline=7.0=ha6073c6_4
- scikit-learn=0.19.1=py35hbf1f462_0
- scipy=1.1.0=py35hfa4b5c9_1
- setuptools=38.4.0=py35_0
- sqlite=3.20.1=hb898158_2
- tk=8.6.7=hc745277_3
- wheel=0.30.0=py35hd3883cf_1
- xz=5.2.3=h55aa19d_2
- zlib=1.2.11=ha838bed_2
- pip:
  - alabaster==0.7.10
  - anyqt==0.0.8
  - argh==0.26.2
  - babel==2.5.3
  - chardet==3.0.4
  - cycler==0.10.0
  - docutils==0.14
  - idna==2.6
  - imagesize==0.7.1
  - jinja2==2.10
  - livereload==2.5.1
  - markupsafe==1.0
  - matplotlib==2.1.2
  - mkl-fft==1.0.4
  - mkl-random==1.0.1
  - opencv-python==3.4.2.17
  - pathtools==0.1.2
  - port-for==0.3.1
  - pybpod-api==1.5.4
  - pybpod-gui-api==1.0
  - pybpod-gui-plugin==1.4.0
  - pybpod-gui-plugin-session-history==1.3.0b0
  - pybpod-gui-plugin-timeline==1.0.1
  - pybpod-rotaryencoder-module==0
  - pybranch==1.4.0
  - pyforms (/home/ricardo/bitbucket/pythonVideoAnnotator/pyforms)==3.0.1
  - pyforms-generic-editor==1.4.6
  - pygments==2.2.0
  - pyopengl==3.1.0
  - pyopengl-accelerate==3.1.0
  - pyparsing==2.2.0
  - pyqt5==5.10
  - python-dateutil==2.6.1
  - python-video-annotator-models (/home/ricardo/bitbucket/pythonVideoAnnotator/pythonvideoannotator-models)==0.0
  - pythonvideoannotator (/home/ricardo/bitbucket/pythonVideoAnnotator)==2.2.0
  - pytz==2018.3
  - pyyaml==3.12
  - qscintilla==2.10.2
  - requests==2.18.4
  - safe-and-collaborative-architecture==0
  - send2trash==1.4.2
  - simplejson==3.13.2
  - sip==4.19.7
  - six==1.11.0
  - snowballstemmer==1.2.1
  - sphinx==1.6.6
  - sphinx-autobuild==0.7.1
  - sphinx-rtd-theme==0.2.4
  - sphinxcontrib-websupport==1.0.1
  - tornado==4.5.3
  - urllib3==1.22
  - visvis==1.10.0
  - watchdog==0.8.3
prefix: /home/ricardo/miniconda3/envs/videoannotator-environment

