name: videoannotator
channels:
- inso
- conda-forge
- defaults
dependencies:
- certifi=2018.1.18=py35_0
- pip=9.0.1=py35_1
- pyopengl=3.1.1a1=py35_0
- python=3.5.5=0
- setuptools=38.5.2=py35_0
- vs2015_runtime=14.0.25420=0
- wheel=0.30.0=py35_2
- wincertstore=0.2=py35_0
- pyqt5=5.6=py35_0
- sip=4.18=py35_0
- pip:
  - anyqt==0.0.8
  - cycler==0.10.0
  - kiwisolver==1.0.1
  - matplotlib==2.2.0
  - numpy==1.14.1
  - opencv-python==3.4.0.12
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2018.3
  - qscintilla==2.10.3
  - scipy==1.0.0
  - send2trash==1.5.0
  - simplejson==3.13.2
  - six==1.11.0
  - visvis==1.10.0